version: '4'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: votacao-server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - ./dbs/postgres:/var/lib/postgresql/data